### ISSUE TITLE
Doesn't run correctly on nSpire CX, screen glitched

### ISSUE THREAD

**Issue by reasv** [Vogtinator/gpsp#3] opened 2018-04-10 14:27 UTC
I have an nSpire CX -AB with the new screen and this emulator running in compatibility mode still lags significantly even with overclock.

So I tried to compile it myself to get it to run without compat-mode, but it it doesn't work.
Whether I use the version I compiled myself or your release at #1 , while it doesn't start in compatibility mode, it's glitched and only part of the screen is occupied by the program, it also "flickers" a bit.
When I try starting a game, the part of the screen occupied by the emulator becomes white and then it freezes forcing me to reset.

![jpeg_20180410_162031](https://user-images.githubusercontent.com/7143787/38562894-ec00e9f4-3cdb-11e8-807e-6cf92431fb74.jpg)

**Comment by gameblabla** [comment] 2018-05-27 10:31
Looking at the source code, i'm a bit puzzled why it would do this. And i see that Vogt added a RGB555 screen mode and skipped some steps. (presumably in an attempt to make it faster?)
It's also possible that it's simply due to the fact that it is an older build, RGB555 mode at the time was experimental.

Please give my build a try and also update your ndless_resources.tns file to the latest version.
[gpsp_lcd_blit_gcc73build.zip](https://github.com/Vogtinator/gpsp/files/2042496/gpsp_lcd_blit_gcc73build.zip)

**Comment by fghsgh** [comment] 2018-05-27 18:35
I will try it later as I don't have time now. I thought it had something to do with the screen being rotated but not updating the dimensions (320x240 becomes 240x320 but the software keeps sending 320x240, so the first 320 gets cut to 240 and the second 240 causes the right strip to remain). I think my ndless_resources is up-to-date as other programs and games work just fine (both compatibility mode and not).

**Comment by fghsgh** [comment] 2018-05-28 20:36
It's still not working. Only a square is rendered, and games run VERY slowly, like, unplayable slowly.

**Comment by gameblabla** [comment] 2018-05-29 09:59
Sounds like the RGB555 mode is still broken then :/
I think a better idea might be to use the RGB565 mode instead like it used to....
That's something i'm gonna try

**Comment by gameblabla** [comment] 2018-06-10 17:03
@fghsgh I discovered why Gpsp wouldn't work and i managed to make it work without any modifications !
It turns out the version of Ndless_resources shipped on ndless.me is too old and doesn't properly support RGB555.
I compiled the Ndless from source here : https://github.com/Vogtinator/Ndless and it would work properly again.

Remove your ndless_resources.tns file and replace it with that one (after decompressing it of course).
[ndless_res_new.zip](https://github.com/Vogtinator/gpsp/files/2088057/ndless_res_new.zip)

Reboot your calculator & reinstall Ndless again. Try my version of gpsp again and it should work !
Cheers

**Comment by adriweb** [comment] 2018-06-10 17:59
Hmm, upstream is ahead by 20 commits, though, including one that fixes/improves the lcd compat mode, in r2012

**Comment by gameblabla** [comment] 2018-06-10 18:08
@adriweb I did not notice that :P But since he submitted the fix for it, then using his fork is still good.
It fixed the RGB555 color mode for me at least.

**Comment by adriweb** [comment] 2018-06-10 18:15
The ndless.me download just redirects to the latest github release, though. which is the r2012 containing that "(r2012) lcd_compat mode: Save some memory and support transparency" commit...
If it's broken with that, though, maybe you've found a bug :P

**Comment by gameblabla** [comment] 2018-06-10 18:19
@adriweb Yeah, it still links to the older version. He added RGB555 but it wasn't working properly for me. Only after compiling it from source did i fix the issue.

**Comment by gameblabla** [comment] 2018-06-10 18:27
Probably a GCC bug then... I'm not lying, you can try it yourself :eye:

**Comment by adriweb** [comment] 2018-06-10 18:28
lol woops. @Vogtinator any input about this?

**Comment by Vogtinator** [comment] 2018-06-11 17:04
This GPSP fork has  `--ndless-rev-min 2009`, which means it should refuse to run on an older resources version.

If for some reason it still starts, it would not display anything as lcd_blit wouldn't know what to do with RGB555.

This means it's probably a regression introduced by https://github.com/ndless-nspire/Ndless/commit/e71c0e7a324dbc7f8e224fc29f0e40483aa419d1 - which would mean that the OS does weird stuff with that buffer. That would need to be investigated. Can you confirm that it still works with ndless master with that commit reverted?

**Comment by gameblabla** [comment] 2018-06-11 20:50
Well i tried it again by, again, downloading ndless from ndless.me again and it still works with my precompiled gpsp. I mean, it used not to work before on the emulator (same issue as him), what the hell ?
I even tried it with the emulated CR4 screen and it still works with my build.
I also tried to reverse the commit you mentionned Vogtinator and it still works.

Sadly, i don't have my Nspire anymore (will only get it in a few months...) so @fghsgh or @reasv , could you try it again with an updated ndless_resource.tns ?

**Comment by fghsgh** [comment] 2018-06-15 16:04
I have put the ndless_resources.tns @gameblabla sent on my calculator, restarted and re-installed ndless, but it still doesn't work. I have tried both the original version and the version @gameblabla sent above. Can someone send a newly compiled gpsp?

**Comment by Vogtinator** [comment] 2018-06-15 18:05
@gameblabla I had the same -  works fine in firebird but apparently not on real HW.

@fghsgh or @reasv: Can you check whether the battery icon in the top right changes if you plug/unplug the charger?

**Comment by fghsgh** [comment] 2018-06-16 20:48
do you mean in the os?

**Comment by Vogtinator** [comment] 2018-06-16 21:09
No, while gpsp is running and glitched.

**Comment by fghsgh** [comment] 2018-06-18 19:31
Sorry, I can't try it as my battery is fully charged and the battery icon doesn't even update in the OS.

To drain battery, I'm letting it count from 1 to 999999 (which prevents sleep) on full brightness and charging my phone with the USB-cable. It seems the counting will keep it busy for some time.

**Comment by adriweb** [comment] 2018-06-18 23:15
I’m not sure what you mean with the timer stuff in recent hw revs (where did you hear/read that?) but in any case, in the OS, when you plug your calc’s USB the icon should change to indicate that it’s charging (some lightning icon IIRC?) or at least connected, anyway something different. I doubt this has changed on the hardware side...

**Comment by fghsgh** [comment] 2018-06-19 16:52
It did change in the OS, not in the program.

I can't find where I read that. On some forum probably, about the LED. It's not in my history as far as I can see. It was something like "maybe they have put a protection on it, just like you have to write to [memory mapped port address] to enable access to the first timer".

**Comment by Vogtinator** [comment] 2018-06-19 16:58
Ok, that rules out that the OS is somehow interfering with the timing, that means that GPSP itself does it :-/

That also explains why it behaves differently in the emulator. I'll do some tests.

**Comment by Vogtinator** [comment] 2018-06-19 18:15
GPSP does indeed modify the timings and changes from the OS-defined 320x320 (sic!) to 320x240. On a 240x320 LCD that won't work.
By implementing those registers in firebird, I got roughly the same behaviour on GPSP, so this should improve the situation.

I disabled lcd timing changes in this build, please give it a try:
[gpsp_launcher.zip](https://github.com/Vogtinator/gpsp/files/2116386/gpsp_launcher.zip)

**Comment by ThunderRemix** [comment] 2018-06-22 06:13
I've decided to jump into this as I have an nSpire CX CAS -AA model with 4.5.0.1180 installed. I used the ndless_resources.tns in ndless_res_new.zip provided by @gameblabla because the one provided in #1 crashes and reboots the system.
Using the gpsp_launcher.tns from the gpsp_lcd_blit.zip provides the same image as @reasv uploaded. 
The launcher from @gameblabla , gpsp_lcd_blit_gcc73build.zip, has the same issue.

The latest launcher, from @Vogtinator , correctly fills up the screen with the menu. When I launch a ROM, such as Pokemon FireRed, it starts off as a white screen and SLOWLY starts to display the Gamefreak/Nintendo copyright information.

**Comment by Vogtinator** [comment] 2018-06-22 07:00
Ok, so the display issue is fixed, but now it's apparently a performance issue?

**Comment by ThunderRemix** [comment] 2018-06-22 07:36
It's so slow that the original Alpha v0.11, released August 6,2012, is faster.

**Comment by fghsgh** [comment] 2018-06-24 13:47
Same for me as for @ThunderRemix. Can this be the same issue as [this TI-84+ emulator](https://github.com/pbfy0/nspire-z80/issues/2)? That issue is mainly about invalid ROMs but there is also something there about speed.

**Comment by fghsgh** [comment] 2018-06-24 13:50
I found where I have seen the timer lock thing: https://www.omnimaga.org/other-calculator-discussion-and-news/turn-on-the-light-on-the-nspire/ search that page for "timer".

**Comment by ThunderRemix** [comment] 2018-08-18 22:06
Welp, two months later and still nothing. Someone has to send @Vogtinator a newer model calculator. xD

**Comment by Vogtinator** [comment] 2018-09-14 05:30
> EDIT: and the reason the original version does work could be because ndless's compatibility mode takes care of it.

ndless' compatibility mode only intercepts the LCD region and uses the watchdog timer to update the framebuffer periodically.

**Comment by Vogtinator** [comment] 2019-01-28 22:06
This build includes a hack which force-enables caching and buffering for the framebuffer region, please give it a try:

[gpsp_launcher.zip](https://github.com/Vogtinator/gpsp/files/2805152/gpsp_launcher.zip)

**Comment by Vogtinator** [comment] 2019-01-29 20:06
> (It's unstable so you might get flickering and crashes, but all I need to know is whether it runs at acceptable speed)

Here's a stable version:
[gpsp_launcher.zip](https://github.com/Vogtinator/gpsp/files/2809474/gpsp_launcher.zip)

**Comment by BMWeasel** [comment] 2019-01-30 01:02
That reddit guy here, tried the stable version out but when i loaded a ROM the screen turned white and never really changed & took a while to load and respond, although the menu did pop up when i pressed the button. But that might have to do with me mixing up the resources & config folders. =\

**Comment by Vogtinator** [comment] 2019-01-30 09:12
> So, I tried your new stable version, and when I selected a ROM in the menu, it froze. Then, I started spamming buttons (esc, on, menu, F) and suddenly, it started running at a very decent speed. I would probably say it was the correct, original speed, if I had the actual game to try it on my DS Lite.

Which ndless revision and version?

> That reddit guy here, tried the stable version out but when i loaded a ROM the screen turned white and never really changed & took a while to load and respond, although the menu did pop up when i pressed the button. But that might have to do with me mixing up the resources & config folders. =\
>
> Update: The ROM loaded but its even slower than before

Same question: Which ndless revision and version?

**Comment by BMWeasel** [comment] 2019-01-30 10:02
I currently have version 4.5.0

**Comment by fghsgh** [comment] 2019-01-30 13:52
OS: 4.4.0.532
HW: AB
entire product id: P-0417AB
ndless: 4.4.0 r2012, probably the newest in this thread but don't remember
gpsp: the latest stable version you sent

The buttons I was spamming in the previous reply had no effect and it works fine without them. I still have some frameskip though, but games are playable.

**Comment by Vogtinator** [comment] 2019-01-30 13:55
@BMWeasel, @fghsgh: Can you compare to the speed of the "old" gpsp on a pre-W CX calculator?

**Comment by fghsgh** [comment] 2019-01-30 15:24
I don't have one, so that's a bit of a problem. Maybe I can find another GBA emulator for PC somewhere, or I'll record the screen and send a video.

**Comment by Vogtinator** [comment] 2019-02-03 21:30
> Rebooting didn't fix the issue (ctrl+on, then on, not a reset)

That barely does anything except turning off the screen.

> I left it off for a bit longer (maybe one hour) and then it worked again. Does this mean the OS resets the timer sometimes and gpsp relies on that?

If that were the case, the issue would also happen in firebird, but it doesn't.

Does this also apply to the gpsp builds here before the cache tricks?

I'm pretty sure that the issue is caused by the caches, but I don't know which area and how - while the build I uploaded above has a substantial speedup with lcd_blit on my rev D calc, it doesn't seem to work as hoped on W+.

**Comment by fghsgh** [comment] 2019-02-03 21:39
> Does this also apply to the gpsp builds here before the cache tricks?
In those versions, it was so much slower that the current effect would be bottlenecked by the other slowdown.

> If that were the case, the issue would also happen in firebird, but it doesn't.
The thing is that firebird only had HW-W, not HW-AB. And we don't even entirely know how all the hardware works.

> That barely does anything except turning off the screen.
Then how do you explain the fact that it worked after leaving it off for longer? I didn't do anything else besides moving the mouse cursor around a bit, so there is no other difference.

**Comment by Vogtinator** [comment] 2019-02-03 21:42
> The thing is that firebird only has HW-W, not HW-AB. And we don't even entirely know how all the hardware works, so emulating it will never be accurate.

We know how gpsp works though.

> Then how do you explain the fact that it worked after leaving it off for longer? I didn't do anything else besides moving the mouse cursor around a bit, so there is no other difference.

It goes into a deeper power saving mode after a while and at some point shuts down completely. That's configurable in the settings.

**Comment by fghsgh** [comment] 2019-02-03 21:52
> It goes into a deeper power saving mode after a while and at some point shuts down completely. That's configurable in the settings.

Do you mean `Power Standby`? That is `1 Minute`. `Hibernate` is `4 Days`, so that couldn't be it.

Oh look, it's faster again. It may be that 1 minute then.

> We know how gpsp works though.

We know how gpsp works on hardware that we know. If we throw something we know works on one hardware at another hardware it may not work anymore, because of the differences. The differences between pre-W and post-W are quite well researched, but W and AB are not. And we know there are differences because it works on W but doesn't on AB.

**Comment by Vogtinator** [comment] 2019-02-04 07:52
> We know how gpsp works on hardware that we know. If we throw something we know works on one hardware at another hardware it may not work anymore, because of the differences. The differences between pre-W and post-W are quite well researched, but W and AB are not. And we know there are differences because it works on W but doesn't on AB.

That it works on W would be news to me.

**Comment by fghsgh** [comment] 2019-02-04 15:20
> That it works on W would be news to me.

Firebird emulates HW-W, and the description of this program says that it is for HW-W (or so I thought), so I thought it was tested. This would not be the first time something works on W but doesn't on AB. The main issues always seem to be display and timing.

**Comment by Vogtinator** [comment] 2019-02-04 15:52
> Firebird emulates HW-W, and the description of this program says that it is for HW-W (or so I thought), so I thought it was tested.

You misunderstood - the program is for testing on HW-W, not tested on HW-W.

> This would not be the first time something works on W but doesn't on AB. The main issues always seem to be display and timing.

Do you have examples?

**Comment by fghsgh** [comment] 2019-02-04 21:21
> You misunderstood - the program is for testing on HW-W, not tested on HW-W.

Okay. My fault. But given that it worked in Firebird it is quite normal to assume it would work on a real HW-W calculator too.

> Do you have examples?

- nClock (crashes, but claimed to be compatible with W)
- nspire-z80 (currently open issue, works on W but timing issue on AB)
- khicas (just tried, crashed, and never tried again, who needs algebra if you have pen&paper? calculators are just for the games :-P)
- some NES emulator (which worked when fast forward was active but just froze when it wasn't, and even then, on the wrong speed; this was in compatibility mode but still a timing issue on AB)
- I don't actually have too many stuff on my calc so I can't really give a long list, but if this works on W (which it probably does), then there must be some obscure difference between W and AB.

When I got this calc, I immediately started putting programs on it only to find out that most of them didn't work. Gpsp was also one of them until you partially fixed it.

Oh look, it's back to the first speed (the unplayable one) again. I'd say about 30 seconds per frame (with no scaling and frameskip automatic 4 uniform). It just faded from black to the first starting screen. The F button does nothing visible.

Okay, I closed gpsp, went to home screen, turned off, turned on, opened gpsp and it was back to full speed. Odd... This really seems like relying on the OS to set the timer (which was normally always done on W, but on AB sometimes not, it seems to me). How else could you explain the fact that it sometimes works and other times it doesn't, with the only difference being what screen the calc was on when I turned it off and whether gpsp was already run in this session?

I just realized I haven't been thankful enough to you for actually doing all of this. You're actually trying your best to help people (really stubborn ones like me) with their problems and you've been really responsive lately. Thank you.

**Comment by Vogtinator** [comment] 2019-02-05 08:11
> * nspire-z80 (currently open issue, works on W but timing issue on AB)

I haven't heard of that and it's interesting - do you have a link?

> Oh look, it's back to the first speed (the unplayable one) again. I'd say about 30 seconds per frame

I didn't expect it to be that bad - that can only happen if the caches are disabled completely or if the msleep function decides to be a sleep function instead.

Here's a build of gpsp which doesn't use any hardware timing (no msleep, no wait for vblank) in games:
[gpsp_launcher.zip](https://github.com/Vogtinator/gpsp/files/2831247/gpsp_launcher.zip)

**Comment by fghsgh** [comment] 2019-02-05 15:17
> I haven't heard of that and it's interesting - do you have a link?

https://github.com/pbfy0/nspire-z80

I will try your new version later, currently I'm not at a computer to put it on the calc.

**Comment by fghsgh** [comment] 2019-02-05 19:52
> Here's a build of gpsp which doesn't use any hardware timing (no msleep, no wait for vblank) in games:
> [gpsp_launcher.zip](https://github.com/Vogtinator/gpsp/files/2831247/gpsp_launcher.zip)

While the previous version was sometimes slow (2x) but mostly playable once I figured out the reboot trick (just very rarely "very slow"), this one is sometimes slow and mostly very slow (the 30 seconds per frame slow). This is weird. I didn't believe it myself, but I can message you a video if you don't believe me.

I think I'll be reverting to the previous version for now. I also saw a glitch where it showed only the bottom right quarter of the screen, scaled to the full screen (in slowest graphics mode). Fastest graphics is just as slow as slowest though.

Maybe try to use _only_ hardware timing? Just thinking that if disabling hardware timing makes it worse, then maybe enabling it will make it better?

**Comment by Vogtinator** [comment] 2019-02-05 20:01
Ok, so it's neither the framebuffer arera buffer/cache nor timer related.

Are other applications using lcd_blit also affected (try some of the ndless samples and crafti (which doesn't do any timing at all, so it's raw CPU and memory speed))?

**Comment by Vogtinator** [comment] 2019-02-05 20:03
Maybe it's the input scanning (keypad and touchpad) - if you see the same slowdown with crafti I'll upload a version without any input support and a frame limit instead.

**Comment by fghsgh** [comment] 2019-02-05 20:14
> Are other applications using lcd_blit also affected (try some of the ndless samples and crafti (which doesn't do any timing at all, so it's raw CPU and memory speed))?

The ndless samples run in compatibility mode, but particles seems to be just as slow. I think it's skipping frames but I don't know how it's supposed to look. Crafti has been running well once I updated it to the HW-W version, but the problem there was mainly just compatibility mode slowing things down.

> Maybe it's the input scanning (keypad and touchpad) - if you see the same slowdown with crafti I'll upload a version without any input support and a frame limit instead.

No. Even when gpsp is running, the gpsp menu (the blue screen thing) is very responsive. That wouldn't be the case otherwise. Crafti is doing fine. ntxt is also running well in compatibility mode.

**Comment by Vogtinator** [comment] 2019-02-05 21:23
> The ndless samples run in compatibility mode

That's weird - most use lcd_blit by now, like the most interesting one, `link.tns`.

> Crafti has been running well once I updated it to the HW-W version, but the problem there was mainly just compatibility mode slowing things down.

So not a generic caching issue then - at this point crafti and gpsp should do the same stuff, reading input, doing calculations and calling lcd_blit without any waiting in between. gpsp is slightly more complex as it JIT's code for emulation, but I don't think that the culprit is there (otherwise it would rather crash than work slowly).

> Actually, now I look at it, the particles program seems to have a very similar problem.

The particle program is not very efficient and with a lot of particles severe slowdowns are expected. If you have just one or two, it should run smoothly though.

> No. Even when gpsp is running, the gpsp menu (the blue screen thing) is very responsive. You just have to keep the menu key pressed for several seconds before the key is scanned and then it opens the menu quickly. That wouldn't be the case otherwise. Crafti is doing fine. ntxt is also running well in compatibility mode.

Too bad, would've been easier to investigate.

> Just as a side note, it's normal the games take a long time to load, right? (when you select them in the menu, before the game starts, it stays on that blue screen for some time before opening the game)

Yes, the flash and filesystem layers are incredibly slow so loading times ~10s are not unusual.

**Comment by fghsgh** [comment] 2019-02-05 22:00
> The particle program is not very efficient and with a lot of particles severe slowdowns are expected. If you have just one or two, it should run smoothly though.

The thing is that it only ever shows 0, 2 or 3 particles (never 1, and trying to get more resets to 0). Never anything else. And keeping the key pressed for 5 seconds before it reacts (same time as the framerate and also the same as the menu button in gpsp "very slow" mode) doesn't seem very normal to me.

> > The ndless samples run in compatibility mode
> That's weird - most use lcd_blit by now, like the most interesting one, `link.tns`.

Well, after I tried some of them, which were all in compatibility mode and didn't work, I gave up and probably never tried link. Also, this was quite a long time ago. Maybe you're talking about a newer version.

**Comment by Vogtinator** [comment] 2019-02-06 09:04
> EDIT:
I tried link from ndless 4.4 (my OS version) and it was running in compatibility mode, but smoothly. Colors was also responsive to the keypress to quit (I didn't have to keep pressing it for long and it just quit quickly).

You need to use the latest download - ndless 4.5 works fine on OS 4.5. If you use an outdated version there can be issues such as this.

**Comment by fghsgh** [comment] 2019-02-06 11:14
Well, didn't know that. It's kind of confusing that the ndless version looks like the OS version.

**Comment by adriweb** [comment] 2019-02-06 11:51
Ermm, to the contrary, it's done on purpose so that it's easy to know which one is for which OS, no need to keep track of different numbers then. But anyway yeah, use the latest available to avoid potential issues of bugs already fixed.

**Comment by fghsgh** [comment] 2019-02-06 12:49
> no need to keep track of different numbers then.

Well, if my OS is 4.4 and I should use version 4.5, it seems like two different numbers to me. Correct me if I'm wrong.

**Comment by adriweb** [comment] 2019-02-06 14:12
That's the thing: use the Ndless version corresponding to your OS, it's as simple as that :P
But if you want to continue to use Ndless, then don't update your calc's OS whenever a TI update gets out, since it won't be compatible. So... look at the latest ndless version, and install the OS that matches.

**Comment by Vogtinator** [comment] 2019-02-06 14:13
> That's the thing: use the Ndless version corresponding to your OS, it's as simple as that :P

Wrong - use the latest version of Ndless which supports your OS. Ndless 4.5 supports all OSs which there is an installer for back to 3.1.

**Comment by adriweb** [comment] 2019-02-06 14:14
Yes my 2nd sentence solves potential issues for future versions - my first one is true for the time being though :P

**Comment by fghsgh** [comment] 2019-02-06 14:29
Okay, so I'll install ndless 4.5 then.

In the meantime, I found out this while running slower (the 2x one):
- turning off frameskip doesn't slow it down, the frames are closer together (as it should)
- putting it into fast mode will make frameskip higher, and it runs faster, but not as fast as when it's not slowed down, fast mode has basically no effect in that case
- scaled/blended mode (graphics options) is just as fast as unscaled mode

**Comment by BMWeasel** [comment] 2019-07-27 02:29
I just remembered that this existed, 5 months later after finals =|. Either way I thought I would throw the few cents i had left over here. 
HW rev: AC
OS ver: 4.5.0.1180
ndless ver: 4.5.0
So far with the latest version there is no compatibility issue prompt but the games run at 6fpm. the menu button needs to be held down to exit (I'm assuming its just waiting for the next frame[also running overclocked])
If anyone with the skills to work on this gets bored enough to try something I'm here now =P

**Comment by fghsgh** [comment] 2019-07-27 06:13
I'm still here too. The problem are the skills (I'm not very comfortable with the ndless API).

**Comment by Led1-ch** [comment] 2020-02-26 08:30
Not sure if anyone is still working on this but here is my info:
HW rev: AD
OS: 4.5.0.1180
ndless: 4.5.0 (compiled from source 2/26/2020)

So basically I tried every single variation of the gpsp posted in this thread and they were all horrendously slow. The only one that was slightly playable was the one where msleep was disabled and that was still very very slow. On the other hand, gpsp in compatibility mode works completely fine! It is a tad slow even with overclocking so real time games are difficult to play.

I am graduating soon and will have some free time so I'm considering writing a new emulator from scratch so it will be compatible with the new lcd api of ndless. @Vogtinator how much c++ support does ndless have or should I write it completely in c only.

**Comment by Vogtinator** [comment] 2020-02-26 08:50
> @Vogtinator how much c++ support does ndless have or should I write it completely in c only.

Full. I never tried `std::filesystem` though, that might be broken.

**Comment by fghsgh** [comment] 2020-02-26 08:58
@Led1-ch good luck and I'm hoping for the best! Though it did work sometimes with ndless 4.4...

**Comment by Vogtinator** [comment] 2020-03-04 19:01
Please try Ndless with a completely different approach of LCD compatibility from here: https://github.com/ndless-nspire/Ndless/pull/202#issuecomment-594753861

With this, the applications should work much better.

**Comment by fghsgh** [comment] 2020-03-04 20:27
The LCD was already working quite decently, it must be some kind of timer that causes the issue. First time I ran this, it was slow, but not unbearably slow. I think I was maybe getting 2 fps (and the whole gameplay was slowed down, regardless of how much frameskip I set). However, the second time I ran it, it took 63 seconds (and I'm not exaggerating, I stopwatched it) between choosing "Return to game" and seeing the first frame of the game. Then, I had to keep menu pressed for multiple seconds before it would open the menu again. I had to wait out the 60 seconds another time and then I had to press left for another 48 or so before the character moved one frame.

Could you send a version that doesn't try to match the speed to a real GBA? I'm talking about doing what Crafti does and not caring about time too much.

**Comment by Vogtinator** [comment] 2020-03-04 20:30
@fghsgh This approach of using `lcd_blit` is flawed by design and can't really work well, so just try the original gpsp builds instead.

**Comment by fghsgh** [comment] 2020-03-04 20:35
@Vogtinator where can I find that? I suck at GitHub.

**Comment by Led1-ch** [comment] 2020-03-04 20:36
I will try out the new ndless resoures in a few hours but the fact that msleep being disabled significantly speed up the lcd_blit emulator for me means that it's somehow detecting the fps wrong and sleeping too long. But even then I'm not really sure what the issue is. There's also a significant slow down when playing romhacks that do C script insertion instead of straight assembly hacking whereas on the original gpsp it's fine so I'm not sure what's going on there either. Maybe because the C scripts often include checks during the main game loop the nspire can't keep up?

@fghsgh you can find the original build on the ndless apps

**Comment by Vogtinator** [comment] 2020-03-04 20:38
> @Vogtinator where can I find that? I suck at GitHub.

https://www.ticalc.org/archives/files/fileinfo/449/44971.html

> @fghsgh you can find the original build on the ndless apps or on ti-planet. The source code is lost for it I think.

Nope, this repo is based on the tarball. The gbc4nspire sources were lost.

**Comment by fghsgh** [comment] 2020-03-04 20:51
The speed at which that one runs is great. However, the ndless compatibility mode seems broken. It seems to be very stable but it is still unplayable because of the broken compatibility mode. Here is a picture of the Pokemon Firered startscreen:
![compat_mode_broken](https://user-images.githubusercontent.com/15169281/75921897-45dae200-5e62-11ea-98c4-3d462c17f8df.jpg)

**Comment by Vogtinator** [comment] 2020-03-04 20:53
Which HW revision is that calc? It's confirmed to work on HW-Y and below with insufficient data for others.

**Comment by fghsgh** [comment] 2020-03-04 20:53
AB, see above

**Comment by Vogtinator** [comment] 2020-03-04 20:55
Ok, so for Z+ calcs it still needs some work. They probably switched the display model...

**Comment by fghsgh** [comment] 2020-03-04 20:56
...which could explain the first issue with the display only being 240x240.

**Comment by Vogtinator** [comment] 2020-03-04 20:59
No, that was the display initialization code configuring the LCD controller to output 320x240px while drawing 240x320px. That's fixed in https://github.com/Vogtinator/gpsp/commit/b7e972d8e52e8f4097b579618649c11082f4f9ae

**Comment by Led1-ch** [comment] 2020-03-04 21:01
The original build is unstable after about 5 runs it forgets where the bios is for revision AD but the LCD display is fine. Like I said it's about half as slow as pre W revision (i compared to overclocked revision D from my friend)

**Comment by Led1-ch** [comment] 2020-03-05 01:04
Okay so with the new resources and the original gpsp I get a screen similar to fghsgh. Lots of lines everywhere and also tilted the wrong way. With the lcd gpsp I get a black screen after using the menu and I ended up having to restart my calculator. Does this mean that revisions like AB and AD have the pre W dimensions just with an lcd display and that the slowdown on the original gpsp is simply due to the rendering speed and is that fixable? I noticed that the original gpsp was released in 2012 while the SDK graphics for ndless was released in 2013 maybe using that library will fix it?

**Comment by fghsgh** [comment] 2020-03-05 22:39
@Vogtinator You left the IRC room, so I'm writing this here, as it's the only other way I have to contact you:
I restarted the calculator (ctrl + on, on), and the inverting and on/off commands worked. Writing FFFFF caused a dark green, which inverted was magenta. I think this is due to the restart, not because of the I/O the program did. This has also happened on gpsp already. The rectangle was still messed up, though. The read bytes were 0x1ff, 0x01, 0x10a, 0x148.

**Comment by Vogtinator** [comment] 2020-03-06 08:57
> @Vogtinator You left the IRC room, so I'm writing this here, as it's the only other way I have to contact you:

Just write in IRC, I'll read it later.

> I restarted the calculator (ctrl + on, on), and the inverting and on/off commands worked. Writing FFFFF caused a dark green, which inverted was magenta. I think this is due to the restart, not because of the I/O the program did.

Yes, that it works after "restarting" (which is actually just idle mode) can be explained by the OS using SPI to turn the display off and back on again. That the commands now worked means that the communication with the chip still works, just some initialization is missing. Question is now what has to be done, maybe setting CS differently, some GPIO pin or some other hidden clock configuration.

> This has also happened on gpsp already. The rectangle was still messed up, though. The read bytes were 0x1ff, 0x01, 0x10a, 0x148.

When the test program works, the new lcd compatibility mode should work too.

**Comment by Vogtinator** [comment] 2020-03-07 16:08
By calling a different function for sending commands over SPI, the issues on HW-AA+ should be fixed now, please try: https://github.com/ndless-nspire/Ndless/pull/202#issuecomment-594753861

**Comment by fghsgh** [comment] 2020-03-07 19:35
It works! Runs very smoothly. It only freezes now when I press L to load a savestate. I left it on for 15 minutes, but it didn't respond to any keypresses and had to reset again.

**Comment by Led1-ch** [comment] 2020-03-09 19:06
It works wonderfully for me (the original gpsp on compatibility mode). It runs much more closely to pre HW W speed!

**Comment by Vogtinator** [comment] 2020-03-10 19:24
This now restores registers better, please try: https://github.com/ndless-nspire/Ndless/pull/202#issuecomment-594753861

**Comment by Led1-ch** [comment] 2020-03-10 20:11
It works great! Thank you so much for these updates, everything is running great. I also noticed that for some games turning off the music speeds up the game a lot.

**Comment by Vogtinator** [comment] 2020-04-11 13:16
Let's just call this issue fixed then. I'm still hopeful that GPSP can be made to work natively on 240x320, but for now this is good enough.

**Closed by Vogtinator** 2020-04-11 13:16 UTC
